/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health
		 * @description Report the service, the library, the database and the last scan.
		 */
		get: operations['health_api_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/issues': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Issues
		 * @description A filtered, sorted page of issues, with the total behind it.
		 */
		get: operations['list_issues_api_issues_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/issues/{issue_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Issue
		 * @description One issue, with what the parser made of it and its neighbours.
		 */
		get: operations['get_issue_api_issues__issue_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/issues/{issue_id}/cover.jpg': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Cover
		 * @description The issue's cover, rendered on demand when the cache has lost it.
		 */
		get: operations['issue_cover'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/**
		 * Cover
		 * @description The issue's cover, rendered on demand when the cache has lost it.
		 */
		head: operations['issue_cover_head'];
		patch?: never;
		trace?: never;
	};
	'/api/issues/{issue_id}/file': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Issue File
		 * @description Stream an issue's PDF, honouring range and conditional requests.
		 */
		get: operations['issue_file'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/**
		 * Issue File
		 * @description Stream an issue's PDF, honouring range and conditional requests.
		 */
		head: operations['issue_file_head'];
		patch?: never;
		trace?: never;
	};
	'/api/issues/{issue_id}/pages/{page}.webp': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Page Image
		 * @description One page of an issue as a WebP image, rendered on demand.
		 */
		get: operations['issue_page'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/**
		 * Page Image
		 * @description One page of an issue as a WebP image, rendered on demand.
		 */
		head: operations['issue_page_head'];
		patch?: never;
		trace?: never;
	};
	'/api/issues/{issue_id}/progress': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Progress
		 * @description Where the reader got to in one issue.
		 */
		get: operations['get_progress_api_issues__issue_id__progress_get'];
		/**
		 * Put Progress
		 * @description Store where the reader got to, clamped to the issue.
		 */
		put: operations['put_progress_api_issues__issue_id__progress_put'];
		post?: never;
		/**
		 * Remove Progress
		 * @description Forget where the reader got to.
		 */
		delete: operations['remove_progress_api_issues__issue_id__progress_delete'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/issues/{issue_id}/thumb.jpg': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Thumbnail
		 * @description The issue's thumbnail, rendered on demand when the cache has lost it.
		 */
		get: operations['issue_thumb'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		/**
		 * Thumbnail
		 * @description The issue's thumbnail, rendered on demand when the cache has lost it.
		 */
		head: operations['issue_thumb_head'];
		patch?: never;
		trace?: never;
	};
	'/api/libraries': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Libraries
		 * @description Every configured library, with its title and issue counts.
		 */
		get: operations['list_libraries_api_libraries_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/progress': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Progress
		 * @description Every issue with a stored position, most recently read first.
		 */
		get: operations['list_progress_api_progress_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/scan': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Start Scan
		 * @description Start a scan, unless one is already running.
		 *
		 *     The 409 and 503 bodies are returned as plain ``JSONResponse``s, not
		 *     through ``response_model``, so that a conflict can carry the id of
		 *     the scan already running alongside its ``detail`` — a shape
		 *     ``HTTPException`` cannot produce.
		 */
		post: operations['start_scan_api_scan_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/scan/status': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Scan Status
		 * @description Report whether a scan is running, and how the last one went.
		 */
		get: operations['scan_status_api_scan_status_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/stats': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Stats
		 * @description What the catalogue holds, and what the caches cost on disk.
		 */
		get: operations['stats_api_stats_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/titles': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Titles
		 * @description Every title, with its latest issue and the span its issues cover.
		 */
		get: operations['list_titles_api_titles_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/titles/{title_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Title
		 * @description One title, with a per-year count of its issues.
		 */
		get: operations['get_title_api_titles__title_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/titles/{title_id}/calendar': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Title Calendar
		 * @description One year of a title as a day → issue map, latest year by default.
		 */
		get: operations['title_calendar_api_titles__title_id__calendar_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/today': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Today
		 * @description The day's newspapers, the latest magazines and what to read next.
		 */
		get: operations['today_api_today_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * Aspect
		 * @description The page box of an issue, in PDF points.
		 *
		 *     Present as soon as the scanner has opened the file; ``null`` until then, so a
		 *     caller that wants to reserve the right amount of space for a cover has to
		 *     cope with not knowing it yet.
		 */
		Aspect: {
			/** Page H */
			page_h: number;
			/** Page W */
			page_w: number;
		};
		/**
		 * Calendar
		 * @description One year of a title, as a day → issue map.
		 */
		Calendar: {
			/** Days */
			days: {
				[key: string]: string;
			};
			/** Year */
			year: number;
			/** Years */
			years: components['schemas']['YearCount'][];
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/**
		 * HealthResponse
		 * @description What ``GET /api/health`` answers with.
		 *
		 *     ``last_scan`` has no default: the endpoint always passes it explicitly,
		 *     ``null`` or a record, so the client sees a field that is always present.
		 */
		HealthResponse: {
			/** Db Ok */
			db_ok: boolean;
			/** Issue Count */
			issue_count: number;
			last_scan: components['schemas']['ScanRecord'] | null;
			/** Library Ok */
			library_ok: boolean;
			/** Library Path */
			library_path: string;
			/** Scanning */
			scanning: boolean;
			/** Status */
			status: string;
			/** Version */
			version: string;
		};
		/**
		 * Issue
		 * @description One issue: a PDF in the library, as the catalogue understands it.
		 */
		Issue: {
			/** Added At */
			added_at: string;
			aspect?: components['schemas']['Aspect'] | null;
			/** Cover Url */
			cover_url: string;
			/**
			 * Date Precision
			 * @enum {string}
			 */
			date_precision: 'day' | 'month' | 'year' | 'none';
			/**
			 * Date Source
			 * @enum {string}
			 */
			date_source: 'filename' | 'mixed' | 'folder' | 'mtime' | 'none';
			/** File Url */
			file_url: string;
			/** Filename */
			filename: string;
			/** Id */
			id: string;
			/** Is Duplicate */
			is_duplicate: boolean;
			/** Issue Date */
			issue_date?: string | null;
			/** Issue Number */
			issue_number?: string | null;
			/**
			 * Kind
			 * @enum {string}
			 */
			kind: 'newspaper' | 'magazine';
			/** Label */
			label: string;
			/** Library Id */
			library_id: string;
			/** Page Count */
			page_count?: number | null;
			progress?: components['schemas']['Progress'] | null;
			/** Rel Path */
			rel_path: string;
			/** Size */
			size: number;
			/** Thumb Url */
			thumb_url: string;
			/** Title Id */
			title_id: string;
			/** Title Name */
			title_name: string;
		};
		/**
		 * IssueDetail
		 * @description An issue, plus everything only its own page needs.
		 */
		IssueDetail: {
			/** Added At */
			added_at: string;
			aspect?: components['schemas']['Aspect'] | null;
			/** Cover Url */
			cover_url: string;
			/**
			 * Date Precision
			 * @enum {string}
			 */
			date_precision: 'day' | 'month' | 'year' | 'none';
			/**
			 * Date Source
			 * @enum {string}
			 */
			date_source: 'filename' | 'mixed' | 'folder' | 'mtime' | 'none';
			/** Derived Title */
			derived_title: string;
			/** File Url */
			file_url: string;
			/** Filename */
			filename: string;
			/** Id */
			id: string;
			/** Is Duplicate */
			is_duplicate: boolean;
			/** Issue Date */
			issue_date?: string | null;
			/** Issue Number */
			issue_number?: string | null;
			/**
			 * Kind
			 * @enum {string}
			 */
			kind: 'newspaper' | 'magazine';
			/** Label */
			label: string;
			/** Library Id */
			library_id: string;
			/** Matched Rule */
			matched_rule: string;
			/** Next Issue Id */
			next_issue_id?: string | null;
			/** Page Count */
			page_count?: number | null;
			/** Pages Url Template */
			pages_url_template: string;
			/** Prev Issue Id */
			prev_issue_id?: string | null;
			progress?: components['schemas']['Progress'] | null;
			/** Rel Path */
			rel_path: string;
			/** Size */
			size: number;
			/** Thumb Url */
			thumb_url: string;
			/** Title Id */
			title_id: string;
			/** Title Name */
			title_name: string;
		};
		/**
		 * IssuePage
		 * @description A page of issues, with the total the filters matched.
		 */
		IssuePage: {
			/** Items */
			items: components['schemas']['Issue'][];
			/** Total */
			total: number;
		};
		/**
		 * Library
		 * @description One configured library and what the catalogue holds for it.
		 */
		Library: {
			/** Id */
			id: string;
			/** Issue Count */
			issue_count: number;
			/**
			 * Kind
			 * @enum {string}
			 */
			kind: 'newspaper' | 'magazine';
			/** Name */
			name: string;
			/** Path */
			path: string;
			/** Title Count */
			title_count: number;
			/** Unsorted Count */
			unsorted_count: number;
		};
		/**
		 * Progress
		 * @description Where the reader got to in an issue.
		 */
		Progress: {
			/** Page */
			page: number;
			/** Page Count */
			page_count?: number | null;
			/** Updated At */
			updated_at: string;
		};
		/**
		 * ProgressRecord
		 * @description One row of the progress table, as its own endpoints return it.
		 */
		ProgressRecord: {
			/** Issue Id */
			issue_id: string;
			/** Page */
			page: number;
			/** Page Count */
			page_count?: number | null;
			/** Updated At */
			updated_at: string;
		};
		/**
		 * ProgressUpdate
		 * @description The body of ``PUT /api/issues/{id}/progress``.
		 */
		ProgressUpdate: {
			/**
			 * Page
			 * @description 1-based page number; clamped to the issue's page count
			 */
			page: number;
		};
		/**
		 * ScanAccepted
		 * @description What ``POST /api/scan`` answers with when it accepts.
		 */
		ScanAccepted: {
			/** Scan Id */
			scan_id: number;
		};
		/**
		 * ScanProgress
		 * @description A scan already in progress, as ``GET /api/scan/status`` reports it.
		 *
		 *     ``covers_total`` is ``null`` during the ``catalogue`` phase — the fast
		 *     phase never counts the files it will find before it has walked them —
		 *     and known from the first ``covers`` snapshot onward. It has no default:
		 *     every snapshot carries it explicitly, ``null`` or not, so the generated
		 *     client sees a field that is always there rather than one that might be
		 *     missing.
		 *
		 *     ``covers_done`` counts successes only; a cover the pool could not render
		 *     is ``covers_failed`` instead, so a bar or an "N of M" line wants
		 *     ``covers_done + covers_failed`` to reach ``covers_total`` even when some
		 *     of that N were failures.
		 */
		ScanProgress: {
			/** Added */
			added: number;
			/** Covers Done */
			covers_done: number;
			/** Covers Failed */
			covers_failed: number;
			/** Covers Total */
			covers_total: number | null;
			/** Elapsed */
			elapsed: number;
			/** Errors */
			errors: number;
			/** Files Seen */
			files_seen: number;
			/**
			 * Phase
			 * @enum {string}
			 */
			phase: 'catalogue' | 'covers';
			/** Removed */
			removed: number;
			/** Scan Id */
			scan_id: number;
			/** Started At */
			started_at: string;
			/** Updated */
			updated: number;
		};
		/**
		 * ScanRecord
		 * @description One row of the ``scans`` table, the only place the timestamps live.
		 */
		ScanRecord: {
			/** Added */
			added?: number | null;
			/** Covers Done */
			covers_done?: number | null;
			/** Errors */
			errors?: number | null;
			/** Files Seen */
			files_seen?: number | null;
			/** Finished At */
			finished_at?: string | null;
			/** Id */
			id: number;
			/** Message */
			message?: string | null;
			/** Removed */
			removed?: number | null;
			/** Started At */
			started_at?: string | null;
			/** Status */
			status?: string | null;
			/** Updated */
			updated?: number | null;
		};
		/**
		 * ScanStatus
		 * @description What ``GET /api/scan/status`` answers with.
		 *
		 *     ``current`` is ``null`` when the scheduler is idle. Between a scan being
		 *     accepted and its first snapshot it is a ``catalogue`` snapshot with every
		 *     counter at zero, never ``null`` while ``running`` is ``true``. Neither
		 *     field carries a default — every caller passes both explicitly — so the
		 *     client sees them as always-present-but-nullable, not possibly missing.
		 */
		ScanStatus: {
			current: components['schemas']['ScanProgress'] | null;
			last: components['schemas']['ScanSummary'] | null;
			/** Running */
			running: boolean;
		};
		/**
		 * ScanSummary
		 * @description A finished scan, as the scheduler remembers it in memory.
		 */
		ScanSummary: {
			/** Added */
			added: number;
			/** Covers Done */
			covers_done: number;
			/** Duration */
			duration: number;
			/** Errors */
			errors: number;
			/** Files Seen */
			files_seen: number;
			/** Message */
			message: string | null;
			/** Removed */
			removed: number;
			/** Scan Id */
			scan_id: number;
			/** Status */
			status: string;
			/** Updated */
			updated: number;
		};
		/**
		 * Stats
		 * @description What the catalogue holds and what it costs on disk.
		 */
		Stats: {
			/** Covers Bytes */
			covers_bytes: number;
			/** Db Bytes */
			db_bytes: number;
			/** Duplicate Count */
			duplicate_count: number;
			/** Issue Count */
			issue_count: number;
			/** Libraries */
			libraries: components['schemas']['Library'][];
			/** Pages Bytes */
			pages_bytes: number;
			/** Title Count */
			title_count: number;
		};
		/**
		 * Title
		 * @description A periodical: the issues of one name inside one library.
		 */
		Title: {
			/** Cover Url */
			cover_url?: string | null;
			/** First Date */
			first_date?: string | null;
			/** Id */
			id: string;
			/** Issue Count */
			issue_count: number;
			/**
			 * Kind
			 * @enum {string}
			 */
			kind: 'newspaper' | 'magazine';
			/** Last Date */
			last_date?: string | null;
			latest_issue?: components['schemas']['Issue'] | null;
			/** Library Id */
			library_id: string;
			/** Name */
			name: string;
			/**
			 * Source
			 * @enum {string}
			 */
			source: 'config' | 'folder' | 'filename' | 'pattern' | 'unsorted' | 'publication';
			/** Thumb Url */
			thumb_url?: string | null;
		};
		/**
		 * TitleDetail
		 * @description A title, plus the years its issues fall in, newest first.
		 */
		TitleDetail: {
			/** Cover Url */
			cover_url?: string | null;
			/** First Date */
			first_date?: string | null;
			/** Id */
			id: string;
			/** Issue Count */
			issue_count: number;
			/**
			 * Kind
			 * @enum {string}
			 */
			kind: 'newspaper' | 'magazine';
			/** Last Date */
			last_date?: string | null;
			latest_issue?: components['schemas']['Issue'] | null;
			/** Library Id */
			library_id: string;
			/** Name */
			name: string;
			/**
			 * Source
			 * @enum {string}
			 */
			source: 'config' | 'folder' | 'filename' | 'pattern' | 'unsorted' | 'publication';
			/** Thumb Url */
			thumb_url?: string | null;
			/** Years */
			years: components['schemas']['YearCount'][];
		};
		/**
		 * Today
		 * @description The storefront: one day of newspapers, and what to read next.
		 */
		Today: {
			/** Continue Reading */
			continue_reading: components['schemas']['Issue'][];
			/** Date */
			date: string;
			/** Is Today */
			is_today: boolean;
			/** Magazines */
			magazines: components['schemas']['Issue'][];
			/** Newspapers */
			newspapers: components['schemas']['Issue'][];
			/** Newspapers Date */
			newspapers_date?: string | null;
			/** Recently Added */
			recently_added: components['schemas']['Issue'][];
		};
		/** ValidationError */
		ValidationError: {
			/** Context */
			ctx?: Record<string, never>;
			/** Input */
			input?: unknown;
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
		};
		/**
		 * YearCount
		 * @description How many issues of a title carry a date in one year.
		 */
		YearCount: {
			/** Count */
			count: number;
			/** Year */
			year: number;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	health_api_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthResponse'];
				};
			};
		};
	};
	list_issues_api_issues_get: {
		parameters: {
			query?: {
				title?: string | null;
				kind?: ('newspaper' | 'magazine') | null;
				library?: string | null;
				from?: string | null;
				to?: string | null;
				year?: number | null;
				sort?: 'date_desc' | 'date_asc' | 'added_desc';
				limit?: number;
				offset?: number;
				include_duplicates?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IssuePage'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_issue_api_issues__issue_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IssueDetail'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_cover: {
		parameters: {
			query?: {
				/** @description Cache buster: the PDF's mtime */
				v?: string | null;
			};
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The image */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/jpeg': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_cover_head: {
		parameters: {
			query?: {
				/** @description Cache buster: the PDF's mtime */
				v?: string | null;
			};
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The image */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/jpeg': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_file: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The whole document */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/pdf': unknown;
				};
			};
			/** @description The requested range */
			206: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/pdf': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The requested range is not satisfiable */
			416: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_file_head: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The whole document */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/pdf': unknown;
				};
			};
			/** @description The requested range */
			206: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/pdf': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description The requested range is not satisfiable */
			416: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_page: {
		parameters: {
			query?: {
				/** @description Snapped to the next width up */
				w?: number | null;
				/** @description Cache buster: the PDF's mtime */
				v?: string | null;
			};
			header?: never;
			path: {
				issue_id: string;
				page: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The rendered page */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/webp': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such issue, or no such page */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_page_head: {
		parameters: {
			query?: {
				/** @description Snapped to the next width up */
				w?: number | null;
				/** @description Cache buster: the PDF's mtime */
				v?: string | null;
			};
			header?: never;
			path: {
				issue_id: string;
				page: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The rendered page */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/webp': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description No such issue, or no such page */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_progress_api_issues__issue_id__progress_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProgressRecord'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	put_progress_api_issues__issue_id__progress_put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ProgressUpdate'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ProgressRecord'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	remove_progress_api_issues__issue_id__progress_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_thumb: {
		parameters: {
			query?: {
				/** @description Cache buster: the PDF's mtime */
				v?: string | null;
			};
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The image */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/jpeg': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_thumb_head: {
		parameters: {
			query?: {
				/** @description Cache buster: the PDF's mtime */
				v?: string | null;
			};
			header?: never;
			path: {
				issue_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The image */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'image/jpeg': unknown;
				};
			};
			/** @description The client's copy is current */
			304: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_libraries_api_libraries_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Library'][];
				};
			};
		};
	};
	list_progress_api_progress_get: {
		parameters: {
			query?: {
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Issue'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	start_scan_api_scan_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScanAccepted'];
				};
			};
		};
	};
	scan_status_api_scan_status_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ScanStatus'];
				};
			};
		};
	};
	stats_api_stats_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Stats'];
				};
			};
		};
	};
	list_titles_api_titles_get: {
		parameters: {
			query?: {
				kind?: ('newspaper' | 'magazine') | null;
				library?: string | null;
				sort?: 'name' | 'latest';
				include_unsorted?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Title'][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_title_api_titles__title_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				title_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TitleDetail'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	title_calendar_api_titles__title_id__calendar_get: {
		parameters: {
			query?: {
				year?: number | null;
			};
			header?: never;
			path: {
				title_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Calendar'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	today_api_today_get: {
		parameters: {
			query?: {
				/** @description Defaults to today in TZ */
				date?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Today'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
