"""Shared pytest fixtures.

The scanner is tested against the real sample library, generated by
``scripts/make_sample_library.py`` with a fixed ``--today`` so that two runs
produce the same names, the same dates and the same bytes. The generator is
imported rather than shelled out to, which gives the tests its own per-layout
tally: every count asserted below is derived from that tally instead of being
typed out by hand.

The library is built once per session and copied per test, because several tests
delete files, touch them or append to them.
"""

from __future__ import annotations

import datetime as dt
import importlib.util
import shutil
import sys
from collections import Counter
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

import pymupdf
import pytest
import yaml
from fastapi.testclient import TestClient
from PIL import Image

from paperstand.config import Settings
from paperstand.db import issue_id
from paperstand.main import create_app
from paperstand.scanner.covers import TEXT_LIMIT, CoverError, CoverResult, cover_paths
from paperstand.scanner.hashing import content_hash
from paperstand.scanner.scanner import scan_once

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR_PATH = REPO_ROOT / "scripts" / "make_sample_library.py"
EXAMPLE_CONFIG = REPO_ROOT / "paperstand.example.yml"

#: Fixed "today", so that the generated library never moves under the tests.
SAMPLE_TODAY = dt.date(2026, 3, 17)
SAMPLE_DAYS = 14


# ------------------------------------------------------------- fast covers
#
# A scan of the sample library spends most of a second turning each page into
# a 900 px cover and a 300 px thumbnail — real rasterisation, a resize and a
# JPEG encode, twice per issue. Most tests that run a scan never look at the
# rendered pixels; they check that a scan happened, what it counted, or what
# it wrote to the database. For those, `_fast_render_cover` below keeps every
# real number `render_cover` would have reported — page count, page size,
# first page text, and every way a document can be unreadable — and swaps in
# a trivial placeholder image for the two files it writes, which is what
# actually costs the time. A test that inspects the rendered cover or
# thumbnail itself opts back into the real renderer with
# `@pytest.mark.real_covers` (module-level `pytestmark` works too).


def _write_placeholder_jpeg(path: Path) -> None:
    """A tiny, valid JPEG at ``path`` — enough for `has_cover`, not for pixels."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with Image.new("RGB", (2, 2), color=(128, 128, 128)) as placeholder:
        placeholder.save(path, format="JPEG")


def _fast_render_cover(
    pdf_path: Path, identifier: str, cache_root: Path
) -> CoverResult | CoverError:
    """Stand-in for `paperstand.scanner.covers.render_cover`, minus the pixels."""
    try:
        with pymupdf.open(pdf_path) as document:
            if document.needs_pass:
                return CoverError(message="the document is encrypted")
            page_count = document.page_count
            if page_count < 1:
                return CoverError(message="the document has no pages")
            page = document.load_page(0)
            rect = page.rect
            text = page.get_text("text")[:TEXT_LIMIT]
    except Exception as error:  # matches render_cover: never raises
        return CoverError(message=f"{type(error).__name__}: {error}")

    cover, thumbnail = cover_paths(cache_root, identifier)
    _write_placeholder_jpeg(cover)
    _write_placeholder_jpeg(thumbnail)
    return CoverResult(
        page_count=page_count,
        page_w=float(rect.width),
        page_h=float(rect.height),
        first_page_text=text,
        cover=cover,
        thumbnail=thumbnail,
    )


@pytest.fixture(autouse=True)
def _fast_covers(request: pytest.FixtureRequest, monkeypatch: pytest.MonkeyPatch) -> None:
    """Patch the scanner's `render_cover` with the stub above, by default.

    Patched on `paperstand.scanner.scanner`, the only place a scan of the
    sample library calls it from — never on `paperstand.scanner.covers`
    itself, so a test that imports and calls `render_cover` directly (as
    `test_covers.py` does) always exercises the real renderer, marker or not.
    """
    if request.node.get_closest_marker("real_covers") is None:
        monkeypatch.setattr("paperstand.scanner.scanner.render_cover", _fast_render_cover)


@dataclass(frozen=True)
class SampleLibrary:
    """A generated library, with the generator's own per-layout tally."""

    root: Path
    counts: Counter[str]
    today: dt.date

    @property
    def newspaper_files(self) -> int:
        """PDFs written under ``Newspapers/``, date-foldered or declared."""
        return self.counts["Newspapers/YYYY/MM/DD"] + self.counts["Newspapers/<Title> (declared)"]

    @property
    def magazine_files(self) -> int:
        """PDFs written under ``Magazines/``, in every layout."""
        return (
            self.counts["Magazines/<Title>"]
            + self.counts["Magazines/YYYY/<Title>/MM"]
            + self.counts["Magazines/<Title> (declared)"]
        )

    @property
    def zine_files(self) -> int:
        """PDFs written under ``Zines/``."""
        return self.counts["Zines (flat)"]

    @property
    def catalogued_files(self) -> int:
        """Every PDF a scan is expected to catalogue."""
        return self.newspaper_files + self.magazine_files + self.zine_files

    @property
    def ignored_files(self) -> int:
        """Files the walker must never yield."""
        return self.counts["ignored"]

    def path(self, rel_path: str) -> Path:
        """An absolute path inside the library."""
        return self.root / rel_path


def load_generator() -> ModuleType:
    """Import ``scripts/make_sample_library.py`` as a module."""
    if "make_sample_library" in sys.modules:
        return sys.modules["make_sample_library"]
    spec = importlib.util.spec_from_file_location("make_sample_library", GENERATOR_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["make_sample_library"] = module
    spec.loader.exec_module(module)
    return module


def generate_sample_library(out: Path, today: dt.date = SAMPLE_TODAY) -> SampleLibrary:
    """Write the sample library into ``out`` and report what went into it."""
    generator = load_generator()
    out.mkdir(parents=True, exist_ok=True)
    (out / generator.MARKER_NAME).write_text(generator.MARKER_TEXT, encoding="utf-8")
    builder = generator.LibraryBuilder(out)
    generator.build_newspapers(builder, today, SAMPLE_DAYS)
    generator.build_magazines(builder, today.year)
    generator.build_zines(builder, today.year)
    generator.build_publications(builder, today)
    generator.build_noise(builder, today)
    counts: Counter[str] = builder.counts
    return SampleLibrary(root=out, counts=counts, today=today)


@pytest.fixture(scope="session")
def sample_source(tmp_path_factory: pytest.TempPathFactory) -> SampleLibrary:
    """The sample library, generated once for the whole session."""
    return generate_sample_library(tmp_path_factory.mktemp("sample") / "library")


@pytest.fixture
def sample_library(sample_source: SampleLibrary, tmp_path: Path) -> SampleLibrary:
    """A private copy of the sample library, safe to delete files from."""
    root = tmp_path / "library"
    shutil.copytree(sample_source.root, root)
    return SampleLibrary(root=root, counts=sample_source.counts, today=sample_source.today)


def write_sample_config(path: Path) -> None:
    """The example configuration, plus a ``Zines`` library with no titles.

    The example file is the canonical one, so the tests exercise exactly what a
    user is handed; ``Zines`` is added on top of it so that a library whose
    titles are derived rather than configured is covered too.
    """
    config = yaml.safe_load(EXAMPLE_CONFIG.read_text("utf-8"))
    config["libraries"].append({"name": "Zines", "path": "Zines", "kind": "magazine"})
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(config, sort_keys=False, allow_unicode=True), "utf-8")


@pytest.fixture
def data_dir(tmp_path: Path) -> Path:
    """A throwaway ``/data``."""
    data = tmp_path / "data"
    data.mkdir()
    return data


@pytest.fixture
def settings(tmp_path: Path, data_dir: Path) -> Settings:
    """Settings pointing at an empty library and a throwaway data directory."""
    library = tmp_path / "library"
    library.mkdir()
    return quiet_settings(library, data_dir)


@pytest.fixture
def sample_settings(sample_library: SampleLibrary, data_dir: Path) -> Settings:
    """Settings pointing at the sample library and its configuration."""
    settings = quiet_settings(sample_library.root, data_dir)
    write_sample_config(settings.config_path)
    return settings


def quiet_settings(library: Path, data: Path, **overrides: Any) -> Settings:
    """Settings that never scan on their own, so tests decide when they do."""
    values: dict[str, Any] = {
        "library": library,
        "data": data,
        "config": None,
        "static": None,
        "scan_on_start": False,
        "scan_interval": 0,
        "cover_workers": 2,
    }
    values.update(overrides)
    return Settings(**values)


@pytest.fixture(scope="session")
def scanned_data(sample_source: SampleLibrary, tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A ``/data`` holding the sample library already catalogued.

    Scanning means opening a hundred PDFs, so it is done once for the whole
    session and copied per test. An issue's id is derived from its bytes, and
    ``shutil.copytree`` preserves both the bytes and the modification time, so
    every id — and every unchanged row — in this catalogue is exactly as valid
    against each test's private copy of the library as it was against the
    original.

    Session-scoped fixtures are set up before function-scoped ones, so this
    scan always runs before ``_fast_covers`` below has patched anything: every
    cover and thumbnail under this ``/data`` is a real render.
    """
    data = tmp_path_factory.mktemp("scanned") / "data"
    data.mkdir(parents=True)
    settings = quiet_settings(sample_source.root, data)
    write_sample_config(settings.config_path)
    result = scan_once(settings)
    assert result.status == "ok", result.message
    assert result.added > 0
    return data


@pytest.fixture
def catalogue_settings(
    sample_library: SampleLibrary, scanned_data: Path, tmp_path: Path
) -> Settings:
    """Settings over a private, already catalogued copy of the sample library."""
    data = tmp_path / "data"
    shutil.copytree(scanned_data, data)
    return quiet_settings(sample_library.root, data)


@pytest.fixture
def catalogue_client(catalogue_settings: Settings) -> Iterator[TestClient]:
    """Test client for an app serving the catalogued sample library."""
    with TestClient(create_app(catalogue_settings)) as test_client:
        yield test_client


def sample_issue_id(root: Path, rel_path: str) -> str:
    """The id a scan gives the file at ``rel_path``, hashing it directly.

    The scanner derives an issue's id from its content, not its path, so
    computing the id a test expects means hashing the same bytes the scanner
    would have hashed — from wherever this test's own copy of the library
    put them.
    """
    return issue_id(content_hash(root / rel_path))


@pytest.fixture
def client(settings: Settings) -> Iterator[TestClient]:
    """Test client for an app without a frontend build."""
    with TestClient(create_app(settings)) as test_client:
        yield test_client


@pytest.fixture
def sample_client(sample_settings: Settings) -> Iterator[TestClient]:
    """Test client for an app serving the sample library."""
    with TestClient(create_app(sample_settings)) as test_client:
        yield test_client
