"""The committed OpenAPI document, and the script that writes it."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "export_openapi.py"
COMMITTED = REPO_ROOT / "frontend" / "src" / "lib" / "api" / "openapi.json"
GENERATED_CLIENT = REPO_ROOT / "frontend" / "src" / "lib" / "api" / "types.gen.ts"


def load_script() -> ModuleType:
    """Import ``scripts/export_openapi.py`` as a module."""
    if "export_openapi" in sys.modules:
        return sys.modules["export_openapi"]
    spec = importlib.util.spec_from_file_location("export_openapi", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["export_openapi"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def exported() -> str:
    """The document the script produces right now."""
    script = load_script()
    document: dict[str, Any] = script.document()
    rendered: str = script.serialise(document)
    return rendered


def test_the_export_needs_no_library_and_no_database(
    exported: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    """It builds its own throwaway data directory and cleans up after itself."""
    spec = json.loads(exported)

    assert spec["openapi"].startswith("3.")
    assert spec["info"]["title"] == "Paperstand"

    # And it does not fall back to the environment: with `/data` named and not
    # there, the export still succeeds because it never uses that setting.
    monkeypatch.setenv("PAPERSTAND_DATA", "/nowhere/at/all")
    monkeypatch.setenv("PAPERSTAND_LIBRARY", "/nowhere/at/all")
    assert load_script().serialise(load_script().document()) == exported


def test_the_committed_document_is_up_to_date(exported: str) -> None:
    assert COMMITTED.is_file(), "run `make gen-api`"
    assert COMMITTED.read_text("utf-8") == exported, "the document is stale; run `make gen-api`"


def test_check_mode_agrees(tmp_path: Path) -> None:
    script = load_script()

    assert script.main(["--check"]) == 0
    stale = tmp_path / "openapi.json"
    stale.write_text("{}\n", "utf-8")
    assert script.main(["--check", "--out", str(stale)]) == 1
    assert script.main(["--out", str(stale)]) == 0
    assert script.main(["--check", "--out", str(stale)]) == 0


def test_the_document_covers_every_endpoint(exported: str) -> None:
    paths = json.loads(exported)["paths"]

    assert set(paths) == {
        "/api/health",
        "/api/scan",
        "/api/scan/status",
        "/api/stats",
        "/api/libraries",
        "/api/titles",
        "/api/titles/{title_id}",
        "/api/titles/{title_id}/calendar",
        "/api/issues",
        "/api/issues/{issue_id}",
        "/api/issues/{issue_id}/file",
        "/api/issues/{issue_id}/cover.jpg",
        "/api/issues/{issue_id}/thumb.jpg",
        "/api/issues/{issue_id}/pages/{page}.webp",
        "/api/issues/{issue_id}/progress",
        "/api/progress",
        "/api/today",
        "/api/maintenance",
        "/api/maintenance/gaps",
    }
    file_operations = paths["/api/issues/{issue_id}/file"]
    assert set(file_operations) == {"get", "head"}
    # One operation id per operation, or every generator produces broken names.
    ids = [
        operation["operationId"]
        for path in paths.values()
        for operation in path.values()
        if "operationId" in operation
    ]
    assert len(ids) == len(set(ids))


def test_the_typed_client_is_committed_too() -> None:
    assert GENERATED_CLIENT.is_file(), "run `make gen-api`"
    source = GENERATED_CLIENT.read_text("utf-8")
    assert "auto-generated by openapi-typescript" in source
    assert "/api/issues/{issue_id}/pages/{page}.webp" in source


def test_importing_the_application_module_opens_nothing() -> None:
    """``paperstand.main`` must be importable without touching ``/data``."""
    import paperstand.main as main

    assert "app" not in vars(main) or main.__dict__["app"] is not None
    assert callable(main.create_app)
    with pytest.raises(AttributeError):
        main.nothing_of_the_sort  # noqa: B018 - the attribute access is the assertion
